### ISSUE TITLE
Consider changing the title in index.html from "libGDX application" to the project name

### ISSUE THREAD

**Issue by SonicGDX** [libgdx/gdx-liftoff#151]
I can sort of understand why the title in html/webapp/index.html was made [constant](https://raw.githubusercontent.com/libgdx/gdx-liftoff/master/src/main/resources/generator/html/webapp/index.html), but I feel like the biggest reasons to change this are that the (currently - don't know if liftoff will replace it in the near future) official gdx-setup [does](https://raw.githubusercontent.com/libgdx/libgdx/master/extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/war/index) use the project name as the title (as an aside, another thing I noticed when I tested this was that gdx-setup would allow spaces in the project name while liftoff doesn't) and also because it would be more consistent to use the project name since the other platforms do for their equivalents.

**Comment by tommyettinger** [comment]
That's a good point... I can't even think of a time I changed that index.html programmatically, except by using Gradle filters to conditionally remove the superdev button. Filters might be the best way here, too...
