### ISSUE TITLE
Versions are mixed up

### ISSUE THREAD

**Issue by JojoIce** [libgdx/gdx-liftoff#163]
I created a project with 1.12.1.10, and changed the Java Version to 8 since iOS was selected as one platform. When the project is generated, the gdxVersion (!) was set to 8, and Java set to 11 and 22 in the Android project.

If a new project creation is started right away, after the first is created, then the Gdx Version is set to the version that was entered as the java version and the java version is back to 11 (even though mouse over states "8 is advised").

**Comment by tommyettinger** [comment]
Ah, this explains another error that was reported... I don't know how this happened, but it probably is related to preferences from an older Liftoff persisting. I'll look into it right now.

**Comment by tommyettinger** [comment]
OK, I just now was able to reproduce this. It looks like entering anything in the Java version field changes the default libGDX version, 1.12.1, to the Java version.

**Comment by tommyettinger** [comment]
It looks like this was a slightly stripe-y copy-paste error, where changing any field in the box that has the libGDX version would change the libGDX version. This is fixed in the latest commit. I'll push a fixed release soon, but I want to take a look at the other issues raised first.
