### ISSUE TITLE
groovy error

### ISSUE THREAD

**Issue by rohitsaini81** [libgdx/gdx-liftoff#191]
i cause error because of this version :groovyVersion=4.0.2 ,
here is error:-
> Task :core:compileJava FAILED

Execution failed for task ':core:compileJava'.
> Could not resolve all files for configuration ':core:compileClasspath'.
   > Could not find org.codehaus.groovy:groovy-all:4.0.2.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-all/4.0.2/groovy-all-4.0.2.pom
       - https://s01.oss.sonatype.org/org/codehaus/groovy/groovy-all/4.0.2/groovy-all-4.0.2.pom
       - file:/home/rohit/.m2/repository/org/codehaus/groovy/groovy-all/4.0.2/groovy-all-4.0.2.pom
       - https://oss.sonatype.org/content/repositories/snapshots/org/codehaus/groovy/groovy-all/4.0.2/groovy-all-4.0.2.pom
       - https://s01.oss.sonatype.org/content/repositories/snapshots/org/codehaus/groovy/groovy-all/4.0.2/groovy-all-4.0.2.pom
       - https://jitpack.io/org/codehaus/groovy/groovy-all/4.0.2/groovy-all-4.0.2.pom
     Required by:
         project :core

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

then i changed the version of it from gradle.properties to --> groovyVersion=3.0.22
it worked 
note: and i just have downloaded gdx-liftoff so everything was supposed to be updated

**Comment by tommyettinger** [comment]
Ah, interesting. According to https://groovy.apache.org/download.html#buildtools , they changed the dependency needed starting in 4.x versions. The dependency should be `"org.apache.groovy:groovy-all:4.0.22"` now; no one has actually ever used Groovy from Liftoff so no one noticed it fail, I guess. Most people know of it from Gradle configuration, invariably have a bad experience, and so never want to touch it again...

I'll have this fixed before the next release. However, changing the dependency to what Groovy 4.x uses will mean it won't be what Groovy 3.x uses, so downgrading would need manually changing the Gradle files (like what you could do now to upgrade). I think most people probably will want to be on 4.x if they actually want Groovy at all.
