### ISSUE TITLE
Feature request: better Linux executable observation

### ISSUE THREAD

**Issue by FelixDes** [libgdx/gdx-liftoff#200]
Hi dear maintainers,

I have an issue with __Intellij Idea__ executable observation on my Arch Linux machine.
"[Idea](https://github.com/libgdx/gdx-liftoff/blob/8446551b75e1c0da64c70f5f3e33f3cb1e82bff5/src/main/java/gdx/liftoff/ui/panels/CompleteButtonsPanel.java#L71)" alias is not always working properly in case of manually installed software. For example Arch User Repository package has name "intellij-idea-ultimate-edition" by default.

I created a PR that fixes that issue and adds functionality for adding more names in executable resolution flow.

**Comment by FelixDes** [comment]
[Linked PR](https://github.com/libgdx/gdx-liftoff/pull/201)

**Comment by tommyettinger** [comment]
This has now been merged, hooray!
