### ISSUE TITLE
Bug: main class with name `sealed` can be created with Java >=15

### ISSUE THREAD

**Issue by FelixDes** [libgdx/gdx-liftoff#204]
I have noticed that the app allows me to create a main class with the name `sealed`. However, this is not a valid class name in Java starting from version 15.
The project creation flow requests the Java version only after the main class name is set. Therefore, to avoid having to rewrite the entire flow, I propose banning this name, along with other reserved keywords like `int`, `class`, etc.

I created a PR that fixes that issue.

**Comment by FelixDes** [comment]
[Linked issue](https://github.com/libgdx/gdx-liftoff/pull/203)

**Comment by tommyettinger** [comment]
It's been merged, thanks!
