### ISSUE TITLE
Debugging Not Working on MacBook When Using StartupHelper in Intellij

### ISSUE THREAD

**Issue by omarmahamid** [libgdx/gdx-liftoff#213]
When attempting to debug applications using LWJGL3's StartupHelper on MacBook, the debugger fails to connect with the following error:
```text
CopyERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
```

in `StartupHelper`

there is 

```java
jvmArgs.addAll(ManagementFactory.getRuntimeMXBean().getInputArguments())
```

to fix it I should filter the debugging args

`agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=127.0.0.1:49462`

something like

```java
        ManagementFactory.getRuntimeMXBean().getInputArguments().stream()
            .filter(arg -> !arg.contains("-agentlib:jdwp"))
            .filter(arg -> !arg.contains("-Xdebug"))
            .filter(arg -> !arg.contains("-Xrunjdwp"))
            .forEach(jvmArgs::add);
```

**Comment by tommyettinger** [comment]
I don't follow this at all. I'm pretty sure there are other Mac users who would have probably used debugging before, unless you're doing something differently. I don't know what you're debugging with -- IDEA's built-in debugger, something in Eclipse, something else... I also don't know why removing some JVM flags that seem to enable debugging would help you debug. It might help to know if you're using a newer ARM64 MacBook or an earlier x64 MacBook.

**Comment by omarmahamid** [comment]
I able fixing it running with gradle

Thanks.
