### ISSUE TITLE
User Experience

### ISSUE THREAD

**Issue by payne911** [libgdx/gdx-liftoff#22]
Just a collection of small things. The strike-through means it's been done.

1. Missing something closer to a native OS file explorer.
![image](https://user-images.githubusercontent.com/38117856/91804383-4e398d00-ebf9-11ea-91e4-8ab8fb0d5d34.png)
2. The "New Directory" button image should have a `+` instead of a `*`.
![image](https://user-images.githubusercontent.com/38117856/91800854-c8691200-ebf7-11ea-9d9a-d12a67376c71.png)
3. Don't display the "Android SDK" thing when people haven't checked the Android tickbox.
![image](https://user-images.githubusercontent.com/38117856/91800904-e171c300-ebf7-11ea-9ca3-24e72c574581.png)
4. Reorganize the platforms, maybe?
![image](https://user-images.githubusercontent.com/38117856/91800969-09f9bd00-ebf8-11ea-9621-83ad692238b2.png)
5. Do not allow `Shared` in platforms if you don't have `Server` selected.
![image](https://user-images.githubusercontent.com/38117856/91801012-1a119c80-ebf8-11ea-871f-f113452e787e.png)
6. Both ``Desktop`` platform options should be one after another, rather than separated.
![image](https://user-images.githubusercontent.com/38117856/91804686-614c5d00-ebf9-11ea-9b6c-b9142146dd78.png)
7. ~~Remove the two ``Toggle`` buttons: most probably no one uses them.~~
![image](https://user-images.githubusercontent.com/38117856/91804761-67423e00-ebf9-11ea-9068-4b52f5c4e83a.png)
8. Try to figure out how to indicate that there are clickable links that open a browser tab (like those "``?``").
![image](https://user-images.githubusercontent.com/38117856/91801259-5f35ce80-ebf8-11ea-90b3-78afcefdabeb.png)
9. About the image above: how to reconcile with the ``Advanced`` tab which also showcases ``Java`` version selection? I think it should be merged.
10. Prevent selection of the extra ``Languages`` if the ``HTML`` platform was selected?
![image](https://user-images.githubusercontent.com/38117856/91802747-c9e70a00-ebf8-11ea-82f9-14b1a3844a63.png)
11. ~~The descriptions should probably be left-aligned, and then add a bit more padding in between the columns of the table.~~
![image](https://user-images.githubusercontent.com/38117856/91803087-e2efbb00-ebf8-11ea-846c-f8e70a0d543e.png)
12. Do not display "KTX" ``Third-party`` if "Kotlin" isn't select in ``Languages``.
![image](https://user-images.githubusercontent.com/38117856/91803657-1894a400-ebf9-11ea-8890-c92e41aba711.png)
13. Increase the alpha of the background of the tooltips.
![image](https://user-images.githubusercontent.com/38117856/91803890-2a764700-ebf9-11ea-85ad-5fce01f55cbf.png)
14. ~~Remove Polski language translation.~~
![image](https://user-images.githubusercontent.com/38117856/91804042-35c97280-ebf9-11ea-8b53-1a64f3d86c0c.png)
15. Unclutter this based on previous selections: do not give a choice to select a Java version for the server if the ``Server`` platform wasn't selected.
![image](https://user-images.githubusercontent.com/38117856/91805116-8b9e1a80-ebf9-11ea-8eb5-8561da44cfc8.png)
16. Should we allow selection of the Gradle Wrapper version?
![image](https://user-images.githubusercontent.com/38117856/91805288-a2dd0800-ebf9-11ea-8118-86e6bd4f9c47.png)
17. It's weird to have within the same dialog, at the top a gray "Generating", then right below a "Generating new project" in red, and then at the bottom a "Setup complete" in green, all at the same time. This could be reworked a bit.
![image](https://user-images.githubusercontent.com/38117856/91806421-f8b1b000-ebf9-11ea-8c58-0fcc66742b2b.png)
18. All in all, the "flow" of the user's interaction could be rethought, and I think making it more of a "step by step" wizard-approach could eliminate a lot of complexity in terms of "if user has selected X, then don't show Y" and such. But that's a lot of work.

**Comment by tommyettinger** [comment]
14 is already done, 4 and 6 are kinda odd because the platforms are in alphabetical order, 5 is weird because I don't really know what people use Shared for, uh... 16 Gradle wrapper should probably be mandated, it's a hassle otherwise... 17, 13, 11, 9, 7, agreed.  15, 12, 10, 3: there isn't a sequence these happen in; a user could select Kotlin and then select HTML, which would make a partly-non-building project, but they don't actually have to use Kotlin in their app, or could use it only on desktop. This would be fixed in part by 18, but I fairly often jump back to the first tab in practice when I'm setting up a game. 2 I disagree with; that's an accepted icon for making a new folder. 1 will be hard  -- TinyFileDialog may fix it, but I have no experience with it and it probably isn't a scene2d.ui widget. I'm opposed to using JavaFX just for a file dialog.

**Comment by Wasylews** [comment]
Can we have kotlin-based project templates? As I understand [Dark Matter](https://github.com/Quillraven/Dark-Matter) were making it themselves? And also build scripts look more clean than current one.

**Comment by Frosty-J** [comment]
Hi, can this be closed after the UI changes or is there something still relevant in it?

**Comment by raeleus** [comment]
I feel all these have been addressed in some fashion. Thanks.

To quote Payne: "But that's a lot of work."
It was. Oh god it was.

**Comment by tommyettinger** [comment]
Hooray! Closing!
